version: "3.4"
services: 

    database: 
        image: bitnami/postgresql:latest
        environment:
            POSTGRESQL_USERNAME: username
            POSTGRESQL_PASSWORD: p@ssw0rd
            POSTGRESQL_DATABASE: anomaly
        volumes: 
            - "/home/behnam/db/:/var/lib/postgres"
    
    redis:
        image: redis:5
    
    decoder:
        image:
            context: "./decoder"
        environment:
            CELERY_BROKER: redis:6379/1
            REDIS_QUEUE_CORE_DB : 0
            REDIS_QUEUE_DB: 1
            REDIS_QUEUE_HOST: redis

    core:
        image:
            context: "./core"
        environment:
            CELERY_BROKER: redis:6379/1
        volumes: 
            - "/home/prophet/dataset:/dataset"

    backend:
        image:
            context: "./backend"
        ports: 
            - 8000:8000
        environment:
            CELERY_BROKER: redis:6379/1
            DATABASE_URI: "postgresql:///username:p@ssword@database:5432/anomaly"
