version: "3.4"
services: 

    database: 
        image: bitnami/postgresql:latest
        environment: 
            password: p@$$w0rd
        volumes: 
            - "/home/behnam/db/:/var/lib/postgres"
    
    redis:
        image: redis:5
    
    decoder:
        image:
            context: "./decoder"
        environment:
            CELERY_BROKER: redis:6379/1

    core:
        image:
            context: "./core"
        environment:
            CELERY_BROKER: redis:6379/1

    backend:
        image:
            context: "./backend"
        ports: 
            - 8000:8000
        environment:
            CELERY_BROKER: redis:6379/1
            DATABASE_URI: "database"
