version: "3.4"
services: 
    database: 
        image: bitnami/postgresql:latest
        environment: 
            password: sag
        volumes: 
            - "/home/behnam/db/:/var/lib/postgres"
    
    redis:
        image: redis:5
    
    core:
        image:
            context: "./core"
    

    backend:
        image:
            context: "./backend"
        ports: 
            - 8000:8000
        environment:
            CELERY_BROKER: redis:6379/1
            DATABASE_URI: "database"